export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const currencies = [
  { name: "Australian Dollar", code: "AUD" },
  { name: "United States Dollar", code: "USD" },
  { name: "Euro", code: "EUR" },
  { name: "British Pound Sterling", code: "GBP" },
  { name: "Japanese Yen", code: "JPY" },
  { name: "Canadian Dollar", code: "CAD" },
  { name: "Swiss Franc", code: "CHF" },
  { name: "Chinese Yuan", code: "CNY" },
  { name: "Swedish Krona", code: "SEK" },
  { name: "New Zealand Dollar", code: "NZD" },
  { name: "Mexican Peso", code: "MXN" },
  { name: "Singapore Dollar", code: "SGD" },
  { name: "Hong Kong Dollar", code: "HKD" },
  { name: "Norwegian Krone", code: "NOK" },
  { name: "South Korean Won", code: "KRW" },
  { name: "Turkish Lira", code: "TRY" },
  { name: "Russian Ruble", code: "RUB" },
  { name: "Indian Rupee", code: "INR" },
  { name: "Brazilian Real", code: "BRL" },
  { name: "South African Rand", code: "ZAR" },
  { name: "Danish Krone", code: "DKK" },
  { name: "Polish Zloty", code: "PLN" },
  { name: "Israeli New Shekel", code: "ILS" },
  { name: "Saudi Riyal", code: "SAR" },
  { name: "Emirati Dirham", code: "AED" },
  { name: "Czech Koruna", code: "CZK" },
  { name: "Hungarian Forint", code: "HUF" },
  { name: "Thai Baht", code: "THB" },
  { name: "Indonesian Rupiah", code: "IDR" },
  { name: "Malaysian Ringgit", code: "MYR" },
  { name: "Philippine Peso", code: "PHP" },
  { name: "Vietnamese Dong", code: "VND" },
  { name: "Egyptian Pound", code: "EGP" },
  { name: "Ukrainian Hryvnia", code: "UAH" },
  { name: "Romanian Leu", code: "RON" },
  { name: "Chilean Peso", code: "CLP" },
  { name: "Colombian Peso", code: "COP" },
  { name: "Argentine Peso", code: "ARS" },
  { name: "Nigerian Naira", code: "NGN" },
  { name: "Kenyan Shilling", code: "KES" },
  { name: "Bangladeshi Taka", code: "BDT" },
  { name: "Peruvian Sol", code: "PEN" },
  { name: "Kuwaiti Dinar", code: "KWD" },
  { name: "Qatari Riyal", code: "QAR" },
  { name: "Costa Rican Colon", code: "CRC" },
  { name: "Panamanian Balboa", code: "PAB" },
  { name: "Uruguayan Peso", code: "UYU" },
  { name: "Omani Rial", code: "OMR" },
  { name: "Bahraini Dinar", code: "BHD" },
  { name: "Jordanian Dinar", code: "JOD" },
  { name: "Tunisian Dinar", code: "TND" },
  { name: "Moroccan Dirham", code: "MAD" },
  { name: "Guatemalan Quetzal", code: "GTQ" },
  { name: "Honduran Lempira", code: "HNL" },
  { name: "Dominican Peso", code: "DOP" },
  { name: "Nicaraguan Cordoba", code: "NIO" },
  { name: "Paraguayan Guarani", code: "PYG" },
  { name: "Salvadoran Colon", code: "SVC" },
  { name: "Belize Dollar", code: "BZD" },
  { name: "Bulgarian Lev", code: "BGN" },
  { name: "Mauritian Rupee", code: "MUR" },
  { name: "Fijian Dollar", code: "FJD" },
  { name: "Tongan Pa'anga", code: "TOP" },
  { name: "Tanzanian Shilling", code: "TZS" },
  { name: "Ugandan Shilling", code: "UGX" },
  { name: "Zambian Kwacha", code: "ZMW" },
  { name: "Namibian Dollar", code: "NAD" },
  { name: "Botswana Pula", code: "BWP" },
  { name: "Zimbabwean Dollar", code: "ZWL" },
  { name: "Angolan Kwanza", code: "AOA" },
  { name: "Namibian Dollar", code: "NAD" },
  { name: "Mozambican Metical", code: "MZN" },
  { name: "Ethiopian Birr", code: "ETB" },
  { name: "Rwandan Franc", code: "RWF" },
  { name: "Malawian Kwacha", code: "MWK" },
  { name: "Botswana Pula", code: "BWP" },
  { name: "Mauritian Rupee", code: "MUR" },
  { name: "Seychellois Rupee", code: "SCR" },
  { name: "Lesotho Loti", code: "LSL" },
  { name: "Swazi Lilangeni", code: "SZL" },
  { name: "Comorian Franc", code: "KMF" },
  { name: "Burundian Franc", code: "BIF" },
  { name: "Djiboutian Franc", code: "DJF" },
  { name: "Eritrean Nakfa", code: "ERN" },
  { name: "Sudanese Pound", code: "SDG" },
  { name: "South Sudanese Pound", code: "SSP" },
  { name: "Somali Shilling", code: "SOS" },
  { name: "Ghanaian Cedi", code: "GHS" },
];
